server:
  port: 8081
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082  # 微服务地址
          predicates:
            - Path=/user/**            # 请求路径匹配 /user/**
        - id: product-service
          uri: http://localhost:8083
          predicates:
            - Path=/product/**           # 请求路径匹配 /order/**
  application:
    name: geteway-service  # 服务名，注册到 Nacos 上显示的名字
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   # Nacos Server 地址
        namespace: public            # 可选，命名空间
        service: geteway-service     # 可选，不写默认用 application.name
      config:
        server-addr: 127.0.0.1:8848
        namespace: public
        file-extension: yaml